name: Node.js CI/CD
run-name: ${{ github.actor }} is pushing a change

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:  
  contents: write
  
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js LATEST
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - run: npm install
      - run: npm run build
      - name: Code builded
        uses: actions/upload-artifact@v3
        with:
          name: build-code
          path: |
            .git
            build
            src
            package.json
            package-lock.json
      
  testing:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - run: |
          cd build-code
          ls -la
          npm install
          npm test -- --watchAll=false
  
  deployment:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - run: cd build-code && mv * ../

          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
          
  
